## M3C 2018 Lab 2 task 1 solution

1) Use the *rand* function to generate a 3 x 3 matrix, N 

In [4]:
from numpy.random import rand
N = rand(3,3)
print(N)

[[ 0.23091585  0.87908197  0.18642086]
 [ 0.2826943   0.35014611  0.03587661]
 [ 0.72956215  0.9560334   0.86697742]]


2) Compute the eigenvalues and eigenvectors of N:

In [9]:
import numpy as np
l,v = np.linalg.eig(N)
print('eigenvalues:',l)
print('eigenvectors (columns):\n',v)

eigenvalues: [ 1.22861854 -0.23060605  0.45002687]
eigenvectors (columns):
 [[ 0.29433593  0.88161008 -0.20909644]
 [ 0.13336667 -0.41528896 -0.25246262]
 [ 0.94635072 -0.22427381  0.94474404]]


3) Verify that $\textrm{det}(N-\lambda_1 I)=0$ where $\lambda_1$ is the first eigenvalue of N:

In [10]:
l1 = l[0]
I = np.eye(3)
check = np.linalg.det(N-np.dot(l1,I))
print(check)

1.47689859233e-15


4) Verify that $N v_1 = \lambda_1 v_1$ where $v_1$ is the first eigenvector of N:

In [12]:
v1 = v[:,0]
check = np.dot(N,v1)-l1*v1
print(check)

[  5.55111512e-16   1.38777878e-16   1.11022302e-15]
